// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rds

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	SaveRds(ctx context.Context, in *Rds, opts ...grpc.CallOption) (*Rds, error)
	QueryRds(ctx context.Context, in *QueryRdsRequest, opts ...grpc.CallOption) (*RdsSet, error)
	UpdateRds(ctx context.Context, in *UpdateRdsRequest, opts ...grpc.CallOption) (*Rds, error)
	DescribeRds(ctx context.Context, in *DescribeRdsRequest, opts ...grpc.CallOption) (*Rds, error)
	DeleteRds(ctx context.Context, in *DeleteRdsRequest, opts ...grpc.CallOption) (*Rds, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) SaveRds(ctx context.Context, in *Rds, opts ...grpc.CallOption) (*Rds, error) {
	out := new(Rds)
	err := c.cc.Invoke(ctx, "/ericyaoxr.cmdb.rds.Service/SaveRds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) QueryRds(ctx context.Context, in *QueryRdsRequest, opts ...grpc.CallOption) (*RdsSet, error) {
	out := new(RdsSet)
	err := c.cc.Invoke(ctx, "/ericyaoxr.cmdb.rds.Service/QueryRds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpdateRds(ctx context.Context, in *UpdateRdsRequest, opts ...grpc.CallOption) (*Rds, error) {
	out := new(Rds)
	err := c.cc.Invoke(ctx, "/ericyaoxr.cmdb.rds.Service/UpdateRds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DescribeRds(ctx context.Context, in *DescribeRdsRequest, opts ...grpc.CallOption) (*Rds, error) {
	out := new(Rds)
	err := c.cc.Invoke(ctx, "/ericyaoxr.cmdb.rds.Service/DescribeRds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DeleteRds(ctx context.Context, in *DeleteRdsRequest, opts ...grpc.CallOption) (*Rds, error) {
	out := new(Rds)
	err := c.cc.Invoke(ctx, "/ericyaoxr.cmdb.rds.Service/DeleteRds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	SaveRds(context.Context, *Rds) (*Rds, error)
	QueryRds(context.Context, *QueryRdsRequest) (*RdsSet, error)
	UpdateRds(context.Context, *UpdateRdsRequest) (*Rds, error)
	DescribeRds(context.Context, *DescribeRdsRequest) (*Rds, error)
	DeleteRds(context.Context, *DeleteRdsRequest) (*Rds, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) SaveRds(context.Context, *Rds) (*Rds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRds not implemented")
}
func (UnimplementedServiceServer) QueryRds(context.Context, *QueryRdsRequest) (*RdsSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRds not implemented")
}
func (UnimplementedServiceServer) UpdateRds(context.Context, *UpdateRdsRequest) (*Rds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRds not implemented")
}
func (UnimplementedServiceServer) DescribeRds(context.Context, *DescribeRdsRequest) (*Rds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeRds not implemented")
}
func (UnimplementedServiceServer) DeleteRds(context.Context, *DeleteRdsRequest) (*Rds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRds not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_SaveRds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SaveRds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ericyaoxr.cmdb.rds.Service/SaveRds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SaveRds(ctx, req.(*Rds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_QueryRds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).QueryRds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ericyaoxr.cmdb.rds.Service/QueryRds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).QueryRds(ctx, req.(*QueryRdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UpdateRds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UpdateRds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ericyaoxr.cmdb.rds.Service/UpdateRds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UpdateRds(ctx, req.(*UpdateRdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DescribeRds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DescribeRds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ericyaoxr.cmdb.rds.Service/DescribeRds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DescribeRds(ctx, req.(*DescribeRdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DeleteRds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DeleteRds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ericyaoxr.cmdb.rds.Service/DeleteRds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DeleteRds(ctx, req.(*DeleteRdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ericyaoxr.cmdb.rds.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveRds",
			Handler:    _Service_SaveRds_Handler,
		},
		{
			MethodName: "QueryRds",
			Handler:    _Service_QueryRds_Handler,
		},
		{
			MethodName: "UpdateRds",
			Handler:    _Service_UpdateRds_Handler,
		},
		{
			MethodName: "DescribeRds",
			Handler:    _Service_DescribeRds_Handler,
		},
		{
			MethodName: "DeleteRds",
			Handler:    _Service_DeleteRds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/rds/pb/rds.proto",
}
